-- 코드를 입력하세요
WITH TOTAL_SALES AS (
    SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
    FROM BOOK_SALES BS
    JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
    JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
    WHERE TO_CHAR(BS.SALES_DATE, 'YYYYMM') = '202201'
    GROUP BY B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.PRICE
)

SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES)
FROM TOTAL_SALES
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC
