-- 코드를 입력하세요
SELECT CP.CART_ID
FROM CART_PRODUCTS CP
WHERE EXISTS (SELECT CP2.CART_ID FROM CART_PRODUCTS CP2 WHERE CP2.CART_ID = CP.CART_ID AND NAME = 'Milk')
AND EXISTS (SELECT CP3.CART_ID FROM CART_PRODUCTS CP3 WHERE CP3.CART_ID = CP.CART_ID AND NAME = 'Yogurt')
GROUP BY CP.CART_ID
ORDER BY CP.CART_ID