--with으로 테이블 만들면서 푸니까 가독성 쥑이네~~

WITH RENTALABLE_CAR AS (
    SELECT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR A
    WHERE NOT EXISTS(SELECT B.CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B WHERE A.CAR_ID = B.CAR_ID 
                    AND B.START_DATE <= DATE '2022-11-30' AND B.END_DATE >= DATE '2022-11-01')
),
MONTH_FEE AS(
    SELECT RC.CAR_ID, RC.CAR_TYPE, (RC.DAILY_FEE * 30 * (100-DISCOUNT_RATE) / 100) AS FEE
    FROM RENTALABLE_CAR RC, CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    WHERE RC.CAR_TYPE = DP.CAR_TYPE
    AND DP.DURATION_TYPE = '30일 이상'
)
SELECT *
FROM MONTH_FEE
WHERE FEE BETWEEN '500000' AND '2000000'




--와 WITH 활용하는거 넘 좋다
--절대 까먹지 말자!!!
WITH MAY_ORDER AS(
    SELECT PRODUCT_ID, SUM(AMOUNT) AS TOT_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN DATE '2022-05-01' AND DATE '2022-05-31'
    GROUP BY PRODUCT_ID
),PRODUCT_TOTAL_SALES AS(
    SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, (FP.PRICE * MO.TOT_AMOUNT) AS TOTAL_SALES
    FROM FOOD_PRODUCT FP, MAY_ORDER MO
    WHERE FP.PRODUCT_ID = MO.PRODUCT_ID
)
SELECT PRODUCT_ID, PRODUCT_NAME, TOTAL_SALES
FROM PRODUCT_TOTAL_SALES
ORDER BY TOTAL_SALES DESC, PRODUCT_ID
