
WITH RANKED_ORDER AS(
SELECT FLAVOR, RANK() OVER(ORDER BY SUM(TOTAL_ORDER) DESC) AS RANK
FROM(
    SELECT * FROM FIRST_HALF 
    UNION ALL
    SELECT * FROM JULY)
    
GROUP BY FLAVOR)

SELECT FLAVOR FROM RANKED_ORDER WHERE ROWNUM <=3

--RANK() OVER(ORDER BY )
--정렬하고 ROWNUM으로 가져와도 됨
--UNION 중복제거
--UNION ALL 중복안제거 ㅋ
