-- 코드를 입력하세요
WITH SALES_TABLE AS (

    SELECT PR.PRODUCT_CODE, SUM(PR.PRICE * OS.SALES_AMOUNT) AS SALES
    FROM PRODUCT PR 
    JOIN OFFLINE_SALE OS ON PR.PRODUCT_ID = OS.PRODUCT_ID
    GROUP BY PR.PRODUCT_CODE
)

SELECT *
FROM SALES_TABLE
ORDER BY SALES DESC, PRODUCT_CODE