WITH JOIN_2021 AS (
    SELECT USER_ID FROM USER_INFO WHERE EXTRACT(YEAR FROM JOINED) = '2021'
), PURCHASED_JOIN_2021 AS (
    SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR, EXTRACT(MONTH FROM SALES_DATE) AS MONTH, COUNT(DISTINCT USER_ID) AS PURCHASED_USERS
    FROM ONLINE_SALE
    WHERE USER_ID IN (SELECT USER_ID FROM JOIN_2021)
    GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
)

SELECT YEAR, MONTH, PURCHASED_USERS, ROUND(PURCHASED_USERS / (SELECT COUNT(*) FROM JOIN_2021), 1) AS PUCHASED_RATIO
FROM PURCHASED_JOIN_2021
ORDER BY YEAR, MONTH