-- 코드를 입력하세요
WITH REMAIN_ANIMAL AS(
    SELECT NAME, DATETIME
    FROM ANIMAL_INS AI
    WHERE NOT EXISTS (SELECT ANIMAL_ID FROM ANIMAL_OUTS AO WHERE AI.ANIMAL_ID = AO.ANIMAL_ID)
    ORDER BY DATETIME
)

SELECT NAME, DATETIME
FROM REMAIN_ANIMAL
WHERE ROWNUM <= 3